
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gt.edu.usac.compiler;

/** CUP generated class containing symbol constants. */
public class CsParserSym {
  /* terminals */
  public static final int TIMES = 24;
  public static final int LONG = 15;
  public static final int PLUS = 22;
  public static final int NEG = 12;
  public static final int identifier = 28;
  public static final int RBRACE = 9;
  public static final int RPAREN = 3;
  public static final int INT = 14;
  public static final int CHAR = 20;
  public static final int DECIMAL = 18;
  public static final int SEMI = 5;
  public static final int charValue = 29;
  public static final int AT = 13;
  public static final int LPAREN = 2;
  public static final int LBRACKET = 10;
  public static final int COLON = 7;
  public static final int LBRACE = 8;
  public static final int RBRACKET = 11;
  public static final int intValue = 27;
  public static final int STRING = 19;
  public static final int COMMA = 4;
  public static final int FLOAT = 16;
  public static final int EOF = 0;
  public static final int DIV = 25;
  public static final int doubleValue = 26;
  public static final int MINUS = 23;
  public static final int error = 1;
  public static final int DOT = 6;
  public static final int BOOL = 21;
  public static final int DOUBLE = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "SEMI",
  "DOT",
  "COLON",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "NEG",
  "AT",
  "INT",
  "LONG",
  "FLOAT",
  "DOUBLE",
  "DECIMAL",
  "STRING",
  "CHAR",
  "BOOL",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "doubleValue",
  "intValue",
  "identifier",
  "charValue"
  };
}

